Add support for useKey option
akameco/babel-plugin-react-intl-auto pull request #67
Opened 2019-03-09 16:37 UTC by shahyar

**What**: Adds a new `useKey` option.

**Why**: When `useKey = true`, calling `FormattedMessage` or `FormattedHTMLMessage` with a `key` prop will attempt to use `key` as the ID suffix, instead of generating a hash with `defaultMessage`. This is helpful as `FormattedMessage` is much simpler than `defineMessages`, but you still want to benefit from full-path ID generation.

**Checklist**: 

* [x] Documentation
* [x] Tests
* [x] Ready to be merged 
* [ ] Added myself to contributors table  N/A

2019-03-10 00:14 UTC, akameco requested changes
Good idea 👍  Please make some fixes.

2019-03-10 00:14 UTC, akameco commented on readme.md
> +
```suggestion

Type: `boolean` <br>
Default: `false`
```

2019-03-10 00:14 UTC, akameco commented on src/__tests__/components.test.js
> +    tests,
```suggestion
    tests: [defaultTest, keyTest],
```

2019-03-10 00:14 UTC, akameco commented on src/__tests__/__snapshots__/components.test.js.snap
> +<FormattedMessage key="foobar" id="src.__fixtures__.foobar" defaultMessage="hello" />;
👍

2019-03-10 00:14 UTC, akameco commented on readme.md
> +<FormattedMessage id="path.to.file.test.foobar" key="foobar" defaultMessage="hello" />
```suggestion
<FormattedMessage id="path.to.file.foobar" key="foobar" defaultMessage="hello" />
```

2019-03-10 00:17 UTC, akameco commented on src/__tests__/components.test.js
> +    tests,
and `yarn test -u`

2019-03-10 20:22 UTC, shahyar commented
Done!

2019-03-11 05:42 UTC, akameco commented
@shahyar CI is falling. Please update the snapshot.

2019-03-13 22:37 UTC, merged

2019-03-13 23:03 UTC, akameco commented
@shahyar v1.7.0 released. Thank you 👍